// Package v1 hosts the embedded JSON Schemas for vigie: test files and the
// per-chart `.vigie.yaml` configuration file.
//
// Both are generated by the tooling at tools/gen-schema/ — testfile.json from
// the Go structs under internal/dsl, config.json from those under
// internal/config. Run `go generate ./pkg/api/schema/v1/...` (or
// `make check-schema`) to regenerate them after editing either package's types.
package v1

import _ "embed"

//go:generate go run github.com/fregateops/vigie/tools/gen-schema

//go:embed testfile.json
var TestFileSchema []byte

//go:embed config.json
var ConfigSchema []byte
